import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.AbstractAction;
import javax.swing.Action;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 529483
 */
public class AddEmployeeFrame extends javax.swing.JFrame{
    protected int[] error = {0, -1};  
    protected boolean type = false;  
    protected int empNumber;
    protected String firstName;
    protected String lastName;
    protected int sex = -1; // encode e.g. 0 for M, 1 for F, 2 for other
    protected String workLocation = null;
    protected double deductionRate = -1;
    
    // for fte
    protected double yearlySalary = -1;
    
    // for pte
    protected double hourlyWage = -1;
    protected double hoursPerWeek = -1;
    protected double weeksPerYear = -1;
    
    /**
     * Creates new form AddEmployeeFrame
     */
    public AddEmployeeFrame() {
        initComponents();
        //fteEmployeePanel.setVisible(false);
        //yearlySalaryError.setVisible(false);
        resetErrors();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addEmployeePanel = new javax.swing.JPanel();
        addEmployeeLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        maleSelector = new javax.swing.JRadioButton();
        femaleSelector = new javax.swing.JRadioButton();
        otherSelector = new javax.swing.JRadioButton();
        workLocationLabel = new javax.swing.JLabel();
        deductionRateLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        workLocationTextField = new javax.swing.JTextField();
        deductionRateTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        pteEmployeePanel = new javax.swing.JLayeredPane();
        hourlyWageLabel = new javax.swing.JLabel();
        hoursPerWeekLabel = new javax.swing.JLabel();
        weeksPerYearLabel = new javax.swing.JLabel();
        hourlyWageTextField = new javax.swing.JTextField();
        hoursPerWeekTextField = new javax.swing.JTextField();
        weeksPerYearTextField = new javax.swing.JTextField();
        hourlyWageError = new javax.swing.JLabel();
        hoursPerWeekError = new javax.swing.JLabel();
        weeksPerYearError = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        pteSelector = new javax.swing.JRadioButton();
        fteSelector = new javax.swing.JRadioButton();
        empNumberTextField = new javax.swing.JTextField();
        empNumberLabel = new javax.swing.JLabel();
        empNumberError = new javax.swing.JLabel();
        firstNameError = new javax.swing.JLabel();
        lastNameError = new javax.swing.JLabel();
        sexError = new javax.swing.JLabel();
        workLocationError = new javax.swing.JLabel();
        deductionRateError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addEmployeeLabel.setText("add employee");

        firstNameLabel.setText("first name:");

        lastNameLabel.setText("last name:");

        sexLabel.setText("sex:");

        maleSelector.setText("Male");
        maleSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleSelectorActionPerformed(evt);
            }
        });

        femaleSelector.setText("Female");
        femaleSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleSelectorActionPerformed(evt);
            }
        });

        otherSelector.setText("Other");
        otherSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherSelectorActionPerformed(evt);
            }
        });

        workLocationLabel.setText("work location:");

        deductionRateLabel.setText("deduction rate:");

        firstNameTextField.setText("ex. Johnathan");
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        lastNameTextField.setText("ex. Smith");

        workLocationTextField.setText("ex. Mississauga");

        deductionRateTextField.setText("ex. 0.01");

        cancelButton.setText("cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        submitButton.setText("submit");

        hourlyWageLabel.setText("hourly wage:");

        hoursPerWeekLabel.setText("hours per week: ");

        weeksPerYearLabel.setText("weeks per year:");

        hourlyWageTextField.setText("$$$");
        hourlyWageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyWageTextFieldActionPerformed(evt);
            }
        });

        hoursPerWeekTextField.setText("$$$");

        weeksPerYearTextField.setText("$$$");

        hourlyWageError.setText("*");

        hoursPerWeekError.setText("*");

        weeksPerYearError.setText("*");

        pteEmployeePanel.setLayer(hourlyWageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pteEmployeePanel.setLayer(hoursPerWeekLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pteEmployeePanel.setLayer(weeksPerYearLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pteEmployeePanel.setLayer(hourlyWageTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pteEmployeePanel.setLayer(hoursPerWeekTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pteEmployeePanel.setLayer(weeksPerYearTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pteEmployeePanel.setLayer(hourlyWageError, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pteEmployeePanel.setLayer(hoursPerWeekError, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pteEmployeePanel.setLayer(weeksPerYearError, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pteEmployeePanelLayout = new javax.swing.GroupLayout(pteEmployeePanel);
        pteEmployeePanel.setLayout(pteEmployeePanelLayout);
        pteEmployeePanelLayout.setHorizontalGroup(
            pteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pteEmployeePanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(pteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pteEmployeePanelLayout.createSequentialGroup()
                        .addComponent(weeksPerYearLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pteEmployeePanelLayout.createSequentialGroup()
                        .addComponent(hoursPerWeekLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
            .addGroup(pteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pteEmployeePanelLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(pteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hourlyWageError)
                        .addComponent(hoursPerWeekError)
                        .addComponent(weeksPerYearError, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(hourlyWageLabel)
                    .addContainerGap(129, Short.MAX_VALUE)))
        );
        pteEmployeePanelLayout.setVerticalGroup(
            pteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pteEmployeePanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(hourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursPerWeekLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weeksPerYearLabel))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(pteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pteEmployeePanelLayout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addGroup(pteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hourlyWageError)
                        .addComponent(hourlyWageLabel))
                    .addGap(22, 22, 22)
                    .addGroup(pteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hoursPerWeekError)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pteEmployeePanelLayout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(weeksPerYearError)))
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        typeLabel.setText("type:");

        pteSelector.setText("part time employee");
        pteSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pteSelectorActionPerformed(evt);
            }
        });

        fteSelector.setText("full time employee");
        fteSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fteSelectorActionPerformed(evt);
            }
        });

        empNumberTextField.setText("ex. 193825");
        empNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNumberTextFieldActionPerformed(evt);
            }
        });

        empNumberLabel.setText("employee number:");

        empNumberError.setText("*");

        firstNameError.setText("*");

        lastNameError.setText("*");

        sexError.setText("*");

        workLocationError.setText("*");

        deductionRateError.setText("*");

        javax.swing.GroupLayout addEmployeePanelLayout = new javax.swing.GroupLayout(addEmployeePanel);
        addEmployeePanel.setLayout(addEmployeePanelLayout);
        addEmployeePanelLayout.setHorizontalGroup(
            addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addEmployeeLabel)
                    .addGroup(addEmployeePanelLayout.createSequentialGroup()
                        .addComponent(typeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(pteSelector)
                        .addGap(18, 18, 18)
                        .addComponent(fteSelector)))
                .addGap(221, 221, 221))
            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(workLocationError)
                    .addComponent(deductionRateError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEmployeePanelLayout.createSequentialGroup()
                        .addComponent(deductionRateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addEmployeePanelLayout.createSequentialGroup()
                        .addComponent(workLocationLabel)
                        .addGap(18, 18, 18)
                        .addComponent(workLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEmployeePanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(cancelButton)
                        .addGap(29, 29, 29)
                        .addComponent(submitButton))
                    .addGroup(addEmployeePanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empNumberError)
                            .addComponent(firstNameError)
                            .addComponent(lastNameError)
                            .addComponent(sexError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addEmployeePanelLayout.createSequentialGroup()
                                .addComponent(empNumberLabel)
                                .addGap(18, 18, 18)
                                .addComponent(empNumberTextField))
                            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addEmployeePanelLayout.createSequentialGroup()
                                        .addComponent(firstNameLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(firstNameTextField))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addEmployeePanelLayout.createSequentialGroup()
                                        .addComponent(lastNameLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(lastNameTextField))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addEmployeePanelLayout.createSequentialGroup()
                                        .addComponent(sexLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(femaleSelector)
                                        .addGap(18, 18, 18)
                                        .addComponent(maleSelector)))
                                .addGap(18, 18, 18)
                                .addComponent(otherSelector))))
                    .addGroup(addEmployeePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pteEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addEmployeePanelLayout.setVerticalGroup(
            addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addEmployeeLabel)
                .addGap(34, 34, 34)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(pteSelector)
                    .addComponent(fteSelector))
                .addGap(18, 18, 18)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNumberLabel)
                    .addComponent(empNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empNumberError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexLabel)
                    .addComponent(femaleSelector)
                    .addComponent(maleSelector)
                    .addComponent(otherSelector)
                    .addComponent(sexError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workLocationLabel)
                    .addComponent(workLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workLocationError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deductionRateLabel)
                    .addComponent(deductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deductionRateError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pteEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(submitButton))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void empNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNumberTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_empNumberTextFieldActionPerformed

    private void fteSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fteSelectorActionPerformed
        // TODO add your handling code here:
        this.type = false;
        pteEmployeePanel.setVisible(false);
        //fteEmployeePanel.setVisible(false);
        pteSelector.setSelected(false);
        fteSelector.setSelected(true);
    }//GEN-LAST:event_fteSelectorActionPerformed

    private void pteSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pteSelectorActionPerformed
        // TODO add your handling code here:
        this.type = true;
        pteEmployeePanel.setVisible(true);
        pteSelector.setSelected(true);
        fteSelector.setSelected(false);
        //fteEmployeePanel.setVisible(false);
    }//GEN-LAST:event_pteSelectorActionPerformed

    private void hourlyWageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyWageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyWageTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
        this.firstName = firstNameTextField.getText();
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void otherSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherSelectorActionPerformed
        // TODO add your handling code here:
        this.sex = 2;
        femaleSelector.setSelected(false);
        maleSelector.setSelected(false);
    }//GEN-LAST:event_otherSelectorActionPerformed

    private void femaleSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleSelectorActionPerformed
        // TODO add your handling code here:
        this.sex = 1;
        otherSelector.setSelected(false);
        maleSelector.setSelected(false);
    }//GEN-LAST:event_femaleSelectorActionPerformed

    private void maleSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleSelectorActionPerformed
        // TODO add your handling code here:
        this.sex = 0;
        otherSelector.setSelected(false);
        femaleSelector.setSelected(false);
    }//GEN-LAST:event_maleSelectorActionPerformed

    private void setEmpNumber() {
        int tmp = checkToInteger(empNumberTextField.getText());
        if(tmp == -1) {
            // displayError();
        } else {
            this.empNumber = tmp;
        }
    }
    
    private void setFirstName() {
        this.firstName = firstNameTextField.getText();
    }
    
    private void setLastName() {
        this.lastName = lastNameTextField.getText();
    }
    
    private void setWorkLocation() {
        this.workLocation = workLocationTextField.getText();
    }
    
    private void setDeductRate() {
        this.deductionRate = checkToDouble(deductionRateTextField.getText());
    }
    
    private void setYearlySalary() {
        //this.yearlySalary = checkToInteger(yearlySalaryTextField.getText());
    }
    
    private void setWeeksPerYear() {
        this.weeksPerYear = checkToInteger(weeksPerYearTextField.getText());
    }
    
    private void setHoursPerWeek() {
        this.hoursPerWeek = checkToInteger(hoursPerWeekTextField.getText());
    }
    
    private void setHourlyWage() {
        this.hourlyWage = checkToInteger(hourlyWageTextField.getText());
    }
    
    private void resetErrors() {
        empNumberError.setVisible(false);
        firstNameError.setVisible(false);
        lastNameError.setVisible(false);
        sexError.setVisible(false);
        workLocationError.setVisible(false);
        deductionRateError.setVisible(false);
        hourlyWageError.setVisible(false);
        hoursPerWeekError.setVisible(false);
        weeksPerYearError.setVisible(false);
    }
    
    public void setValues() {
        setEmpNumber();
        setFirstName();
        setLastName();
        setWorkLocation();
        setDeductRate();
        setYearlySalary();
        setWeeksPerYear();
        setHoursPerWeek();
        setHourlyWage();
    }
    
    Action action = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e){
            setValues();
        }
    };
    
    private int checkToInteger(String str) {   
        try { 
            return Integer.parseInt(str);
        } catch(Exception e) {
            return -1;
        }
    }
    
    private double checkToDouble(String str) {   
        try { 
            return Double.parseDouble(str);
        } catch(Exception e) {
            return -1;
        }
    }
    
    public PartTimeEmployee createPartTimeEmployee() {
        System.out.println(workLocation);
        return new PartTimeEmployee(empNumber, firstName, lastName, sex, workLocation, deductionRate, hourlyWage, hoursPerWeek, weeksPerYear);
    }
    
    public FullTimeEmployee createFullTimeEmployee() {
        return new FullTimeEmployee(empNumber, firstName, lastName, sex, workLocation, deductionRate, yearlySalary);
    }
   
    public boolean checkError() {
        resetErrors();
        boolean b = false;
        if(error[1] != -1 || empNumber == -1) {
            empNumberError.setVisible(true);
            b = true;
        }
        if(firstName == null) {
            System.out.println(firstName);
            firstNameError.setVisible(true);
            b = true;
        }
        if(lastName == null) {
            lastNameError.setVisible(true);
            b = true;
        }
        if(sex == -1) {
            sexError.setVisible(true);
            b = true;
        }
        if(workLocation == null) {
            workLocationError.setVisible(true);
            b = true;
        }
        if(deductionRate == -1) {
            deductionRateError.setVisible(true);
            b = true;
        }
        if(type) {
            if(weeksPerYear == -1) {
                weeksPerYearError.setVisible(true);
                b = true;
            }
            if(hoursPerWeek == -1) {
                hoursPerWeekError.setVisible(true);
                b = true;
            }
            if(hourlyWage == -1) {
                hourlyWageError.setVisible(true);
                b = true;
            }
        } else {
            if(yearlySalary == -1) {
                //yearlySalaryError.setVisible(true);
                b = true;
            }
        }
        return b;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployeeFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addEmployeeLabel;
    public javax.swing.JPanel addEmployeePanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel deductionRateError;
    private javax.swing.JLabel deductionRateLabel;
    private javax.swing.JTextField deductionRateTextField;
    private javax.swing.JLabel empNumberError;
    private javax.swing.JLabel empNumberLabel;
    private javax.swing.JTextField empNumberTextField;
    private javax.swing.JRadioButton femaleSelector;
    private javax.swing.JLabel firstNameError;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JRadioButton fteSelector;
    private javax.swing.JLabel hourlyWageError;
    private javax.swing.JLabel hourlyWageLabel;
    private javax.swing.JTextField hourlyWageTextField;
    private javax.swing.JLabel hoursPerWeekError;
    private javax.swing.JLabel hoursPerWeekLabel;
    private javax.swing.JTextField hoursPerWeekTextField;
    private javax.swing.JLabel lastNameError;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JRadioButton maleSelector;
    private javax.swing.JRadioButton otherSelector;
    private javax.swing.JLayeredPane pteEmployeePanel;
    private javax.swing.JRadioButton pteSelector;
    private javax.swing.JLabel sexError;
    private javax.swing.JLabel sexLabel;
    protected javax.swing.JButton submitButton;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel weeksPerYearError;
    private javax.swing.JLabel weeksPerYearLabel;
    private javax.swing.JTextField weeksPerYearTextField;
    private javax.swing.JLabel workLocationError;
    private javax.swing.JLabel workLocationLabel;
    private javax.swing.JTextField workLocationTextField;
    // End of variables declaration//GEN-END:variables
}
